# secret containing the goat RPC node URL
# IMPORTANT: replace the base64-encoded value when deploying
#
# to encode your own value:
#   echo -n "https://rpc.goat.network" | base64
apiVersion: v1
kind: Secret
metadata:
  name: goat-monitor-secret
  namespace: goat-network
  labels:
    app.kubernetes.io/name: goat-monitor
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: goat-network
type: Opaque
data:
  # https://rpc.goat.network
  GOAT_RPC_NODE: aHR0cHM6Ly9ycGMuZ29hdC5uZXR3b3Jr
